development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: todo_development
  pool: 5
  username: dwilbank
  password: picasso

test:
  adapter: postgresql
  encoding: unicode
  database: todo_test
  pool: 5
  username: dwilbank
  password: picasso

production:
  adapter: postgresql
  encoding: unicode
  database: todo_production
  pool: 5
  username: dwilbank
  password: picasso
